spring.application.name=pokedex-api
spring.mvc.favicon.enabled=false
server.port=8080

# PokeAPI base URL
pokeapi.base-url=https://pokeapi.co/api/v2

# Cache TTL (seconds)
cache.ttl=600

# Springdoc
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
